"""Need-led pages and honest launch states for proposed community initiatives."""
from pathlib import Path
from html import escape
from urllib.parse import quote
import json

ROOT=Path(__file__).resolve().parent.parent
CONFIG=json.loads((Path(__file__).parent/'growth-content.json').read_text())
NEEDS=[
 ('fit-stark','Fit & stark','Kraft, Ausdauer und Performance.','Für ambitioniertes Training und sportliche Ziele.','/fit-stark/','01'),
 ('gesund-beweglich','Gesund & beweglich','Fit bleiben – in jedem Alter.','Kraft erhalten, Beweglichkeit entwickeln und bewusst einsteigen.','/gesund-beweglich/','02'),
 ('neu-anfangen','Neu anfangen','Dein Einstieg ohne Druck.','Persönliche Orientierung und ein Training, das zu dir passt.','/neu-anfangen/','03'),
 ('gemeinsam','Gemeinsam trainieren','Mehr Motivation. Mehr Gemeinschaft.','Entdecke die Challenge, Friends & Family und unsere Club-Ideen.','/community/','04')
]

def validated_stories():
    stories=[]
    for s in CONFIG['testimonials']:
        required=['name','age','goal','quote','image','source','approved_for_publication']
        if any(k not in s for k in required) or s['approved_for_publication'] is not True:
            raise ValueError('Member stories require source, real photo and explicit publication approval.')
        if any(not isinstance(s[k],str) or not s[k].strip() for k in ['name','goal','quote','image','source']):
            raise ValueError('Member stories require non-empty verified content and source.')
        path=ROOT/s['image']; resolved=path.resolve()
        if ROOT not in resolved.parents or not path.is_file() or type(s['age']) is not int or not 18<=s['age']<=120:
            raise ValueError('Invalid member story asset or age.')
        stories.append(s)
    if CONFIG.get('member_count') is not None and (type(CONFIG['member_count']) is not int or CONFIG['member_count']<1 or not str(CONFIG.get('member_count_source','')).strip()):
        raise ValueError('A member count needs a confirmed positive value and source.')
    if CONFIG['family']['status']!='planned':
        raise ValueError('An active family program needs confirmed terms and an implemented participation flow.')
    return stories

class Growth:
    def __init__(self,ctx):
        self.c=ctx
        self.team={p['slug']:p for p in ctx['TEAM']}
        self.g=ctx['GALLERY'];self.stories=validated_stories()
    def b(self,*a,**kw):return self.c['button'](*a,**kw)
    def link(self,*a):return self.c['textlink'](*a)
    def image(self,*a,**kw):return self.c['img'](*a,**kw)
    def section(self,id,body,cls=''):
        return f'<section class="section growth-section {cls}" id="{id}"><div class="wrap">{body}</div></section>'
    def heading(self,eyebrow,title,lead=''):
        return f'<div class="section-head"><div><p class="eyebrow">{eyebrow}</p><h2>{title}</h2></div>'+ (f'<p class="muted">{lead}</p>' if lead else '')+'</div>'
    def needs(self,compact=False):
        cards=''.join(f'<a class="need-card need-{slug}" href="{url}"><span class="need-number">{n} / DEIN ZIEL</span><h3>{title}</h3><strong>{subtitle}</strong><p>{text}</p><span class="need-arrow" aria-hidden="true">↗</span></a>' for slug,title,subtitle,text,url,n in NEEDS)
        return self.section('dein-ziel',self.heading('Dein Ziel gibt die Richtung vor.','Was möchtest du<br>erreichen?','Dein Alter ist keine Kategorie. Dein Ziel ist der Anfang.')+f'<nav class="needs-grid" aria-label="Training nach deinem Ziel">{cards}</nav>','needs-section'+(' compact' if compact else ''))
    def personal_proof(self):
        if self.stories:
            cards=''.join(f'<figure class="member-story">{self.image(s["image"],s["name"])}<figcaption><p class="eyebrow">{escape(s["name"])} · {s["age"]}</p><p class="story-goal">{escape(s["goal"])}</p><blockquote>„{escape(s["quote"])}“</blockquote></figcaption></figure>' for s in self.stories)
            return self.section('menschen',self.heading('Menschen wie du.','Warum Menschen<br>bei 17/7 bleiben.')+'<div class="stories-grid">'+cards+'</div>')
        p=self.team['beatrice-ulonska']
        return self.section('menschen',f'<div class="human-proof"><div class="human-photo">{self.image(p["asset"],"Beatrice Ulonska, Personal Trainerin im Performance Gym",position="50% 50%")}</div><div class="human-copy"><p class="eyebrow">Persönlichkeit ist kein Extra.</p><h2>Ein Ziel.<br>Ein Mensch an<br>deiner Seite.</h2><blockquote>„{escape(p["overview_excerpt"])}“</blockquote><p class="human-name">Beatrice Ulonska <span>Personal Trainerin bei 17/7</span></p><p>Bring deine Fragen mit. Unsere Personal Trainer stellen sich mit ihren eigenen Profilen vor – damit aus einem ersten Eindruck ein persönlicher Kontakt wird.</p>{self.link('Beatrice kennenlernen','/staff-member/beatrice-ulonska/')}</div></div>','light')
    def team_section(self):
        cards=[]
        for slug in ['guido-leffler','thomas-rossbroich','maike']:
            p=self.team[slug]
            note={'guido-leffler':'Dein Ansprechpartner in der Studioleitung.','thomas-rossbroich':'„Das Geheimnis des Erfolgs ist anzufangen!“','maike':'Ein bekanntes Gesicht im Team vor Ort.'}[slug]
            cards.append(f'<article class="human-card"><a href="/staff-member/{slug}/" class="human-card-photo">{self.image(p["asset"],p["name"],position=p.get("recommended_object_position"))}</a><div><p class="eyebrow">{escape(p["role"])}</p><h3>{escape(p["name"])}</h3><p>{note}</p>{self.link('Profil kennenlernen','/staff-member/'+slug+'/')}</div></article>')
        return self.section('dein-team',self.heading('Inhabergeführt. Persönliche Ansprechpartner.','Kein anonymes Studio.<br>Menschen, die du kennst.','Ob erster Besuch oder feste Routine: Lerne die Menschen hinter 17/7 kennen.')+'<div class="human-cards">'+''.join(cards)+'</div><div class="actions">'+self.link('Das ganze Team kennenlernen','/unser-team/')+'</div>')
    def training_section(self):
        items=[('Kraft','Freie Gewichte und geführte Geräte.','/training/#kraft',self.g[1]),('Cardio','Deine Ausdauer. In deinem Tempo.','/training/#cardio',self.g[6]),('Functional','Bewegung mit vielen Möglichkeiten.','/training/#functional',self.g[0]),('Mobility','Bewusster bewegen. Ausgleich finden.','/training/#mobility',self.g[8])]
        cards=''.join(f'<a href="{url}" class="training-mini"><div>{self.image(photo)}</div><span><h3>{title}</h3><p>{desc}</p><i aria-hidden="true">↗</i></span></a>' for title,desc,url,photo in items)
        return self.section('dein-training',self.heading('Die Möglichkeiten für deinen Weg.','Dein Training.<br>Mit Richtung.','Kraft, Ausdauer, freie Bewegung und Mobilität. Wähle, was zu deinem Ziel passt.')+'<div class="training-mini-grid">'+cards+'</div>')
    def clubs(self,full=False):
        cards=[]
        for i,c in enumerate(CONFIG['clubs']):
            # Ideas have no invented schedule, included benefit or bookable class.
            if c['status']!='planned':raise ValueError('An active club needs an explicitly implemented schedule/booking integration.')
            anchor=c['id'];name=escape(c['name']);url='/contact/?thema='+quote(c['name'])+'#contact-form'
            extra=f'<p class="club-description">{escape(c["description"])}</p><p class="club-focus">{escape(c["focus"])}</p>' if full else ''
            cards.append(f'<article class="club-card" id="{anchor}"><div class="club-card-top"><span>0{i+1}</span><span class="launch-badge">In Planung</span></div><h3>{name}</h3><p class="club-headline">{escape(c["headline"])}</p>{extra}{self.link("Interesse mitteilen" if full else "Format entdecken",url if full else "/community/#"+anchor)}</article>')
        return '<div class="club-grid">'+''.join(cards)+'</div>'
    def community_teaser(self):
        return self.section('community',self.heading('Mehr als dein Training.','Deine 17/7<br>Community.','Neue gemeinsame Formate sind in Planung. Sag uns, was dich bewegt.')+self.clubs()+f'<div class="community-challenge"><div><span class="eyebrow">30 Tage · Dein persönlicher Einstieg</span><h3>Dein Ziel. Dein Rhythmus.<br>Deine WhatsApp-Challenge.</h3><p>Finde deine Ausrichtung mit fünf kurzen Fragen. Dein Startprofil für den nächsten Schritt.</p></div>{self.b("Meine Challenge finden","/whatsapp-challenge/")}</div>')
    def family_teaser(self):
        return self.section('family',f'<div class="family-banner"><div class="family-mark" aria-hidden="true"><span>DU</span><i>+</i><span>DEINE<br>MENSCHEN.</span></div><div><p class="eyebrow">Bring your Mum. Dad. Friend.</p><h2>Gemeinsam<br>stärker.</h2><p>Deine Eltern waren immer für dich da. Vielleicht beginnt euer nächstes gemeinsames Kapitel mit mehr Bewegung. Lade deine Mum, deinen Dad oder einen Freund ein, 17/7 kennenzulernen.</p><div class="actions">{self.b("Persönliche Einladung erstellen","/gemeinsam-starten/#einladen")}</div><p class="growth-fine">Gemeinsames Kennenlernen ist schon möglich. Die begleitete 30-Tage-Family-Challenge ist in Planung.</p></div></div>','family-section')
    def corporate_teaser(self):
        return self.section('firmenfitness',f'<div class="corporate-teaser"><div><p class="eyebrow">Für Unternehmen in Rheinbach.</p><h2>Fit im Job.<br>Gemeinsam bei 17/7.</h2><p>Ein persönliches Gym in der Nachbarschaft. Entdecke Firmenfitness für dein Team – vom bestehenden Firmentarif bis zur Anfrage für gemeinsame Aktionen.</p></div><div>{self.b("Firmenfitness entdecken","/firmenfitness/")}<p>Für Unternehmen im Industriegebiet und in ganz Rheinbach.</p></div></div>','light')
    def final(self):
        return self.section('dein-naechster-schritt',f'<div class="growth-final"><p class="eyebrow">Dein nächster Schritt darf einfach sein.</p><h2>Noch nicht sicher,<br>was zu dir passt?</h2><p>Komm vorbei. Wir finden es gemeinsam heraus.</p><div class="actions">{self.b("Probetraining starten","/probetraining/")}{self.link("Persönlich Kontakt aufnehmen","/contact/#contact-form")}</div><p class="growth-fine">Ohne Termin · Personalausweis & Handtuch mitbringen</p></div>')
    def home(self,instagram):
        member_count=CONFIG.get('member_count');first=(f'{member_count:,}'.replace(',','.')+' Mitglieder','Menschen bei 17/7') if member_count else ('Inhabergeführt','Hier in Rheinbach')
        facts=[('06–22 Uhr','Täglich geöffnet*'),first,('Persönlich','Ansprechpartner vor Ort'),('Dein Level','Einstieg & Erfahrung')]
        trust=''.join(f'<div class="fact"><strong>{escape(a)}</strong><span>{escape(b)}</span></div>' for a,b in facts)
        hero=f'<section class="hero growth-home-hero"><div class="hero-copy"><p class="eyebrow">Das persönliche Gym für Rheinbach.</p><h1>Dein Gym.<span>Dein Training.</span></h1><p class="lead">Persönlich. Professionell. Hier in Rheinbach.<br>Inhabergeführtes Training für jedes Alter und jedes Level.</p><div class="actions">{self.b("17/7 kennenlernen","/studio/")}{self.b("Probetraining starten","/probetraining/","secondary",False)}</div><p class="hero-note"><a class="challenge-hero-link" href="/whatsapp-challenge/">Deine 30-Tage-WhatsApp-Challenge ↗</a></p></div><div class="hero-photo">{self.image(self.g[1],"Trainingsfläche im Performance Gym Rheinbach mit Freihanteln, Hantelbänken und Kraftgeräten",eager=True,sizes="(max-width:650px) max(100vw, 100svh), max(50vw, 100svh)")}<span class="image-note">Deine Trainingsfläche. Direkt hier in Rheinbach.</span></div></section><div class="quickfacts growth-trust"><div class="wrap">{trust}</div></div>'
        studio=f'<section class="split light" id="dein-gym"><div class="split-photo">{self.image(self.g[-1])}</div><div class="split-copy"><p class="eyebrow">Warehouse-Charakter. Persönliche Atmosphäre.</p><h2>Ein Gym mit<br>eigenem Charakter.</h2><p>Hohe Hallen, echte Trainingsflächen und ein Team vor Ort. Entdecke dein inhabergeführtes Gym in der Industriestraße in Rheinbach.</p><div class="actions">{self.b("Das Studio entdecken","/studio/","dark")}{self.link("Dein Weg zu uns","/contact/")}</div></div></section>'
        plans=self.section('mitgliedschaften',f'<div class="price-band"><div><p class="eyebrow">Wenn das Gym zu dir passt.</p><h2>Dein Rhythmus.<br>Deine Mitgliedschaft.</h2><p class="lead">Vergleiche Leistungen, Laufzeiten und Kosten in Ruhe. Deine digitale Anmeldung ist über die Tarifübersicht erreichbar.</p><div class="actions">{self.b("Tarife transparent vergleichen","/preise-aktionen/#tarife")}{self.link("Zur digitalen Anmeldung","/mitglied-werden/#anmeldung")}</div></div><div class="price-callout"><span class="eyebrow">Standard</span><div class="price-big">26,99 €<small>pro Monat · 12 Monate Laufzeit</small></div><p>Monatlich zahlbar. Zuzüglich einmalig 19,99 € für das E-Band. Keine Aufnahmegebühr.</p></div></div>')
        faq=self.section('fragen',f'<div class="faq-layout"><div><p class="eyebrow">Vor deinem ersten Besuch.</p><h2>Gut zu wissen.</h2></div>{self.c["faq"]([self.c["CONTENT"]["draft_copy"]["faq"][i] for i in [0,1,2,7]])}</div>','compact')
        return hero+self.needs()+self.personal_proof()+self.training_section()+self.team_section()+self.community_teaser()+self.family_teaser()+studio+instagram+plans+self.corporate_teaser()+faq+self.final()
    def hero(self,title,lead,tag,picture=None,action=None,scroll='Mehr erfahren'):
        return self.c['head'](title,lead,tag,picture,crumb=tag,action=action,scroll_label=scroll).replace('class="page-head ','class="page-head growth-head ')
    def benefits(self,items):
        return '<div class="benefit-grid">'+''.join(f'<article><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>' for i,(a,b) in enumerate(items))+'</div>'
    def build(self):
        page=self.c['page']
        body=self.hero('Stark bleiben.<br>Für alles, was kommt.','Du musst keine Bestleistungen aufstellen. Finde ein Training, das zu deinem Körper, deinem Alltag und deinen Zielen passt.','Gesund & beweglich',{**self.team['guido-leffler']['asset'],'alt':'Guido Leffler, Studioleiter im Performance Gym'},action=('17/7 kennenlernen','/studio/'),scroll='Unverbindlich Probetraining')
        body=body.replace('class="hero-scroll" href="#page-content"','class="hero-scroll" href="/probetraining/"').replace('Unverbindlich Probetraining <span aria-hidden="true">↓','Unverbindlich Probetraining <span aria-hidden="true">↗')
        body+=self.section('dein-einstieg',self.heading('Mehr Möglichkeiten im Alltag.','Dein Leben.<br>Deine Stärke.','Für den Einstieg, den Wiedereinstieg und ein Training, das dich langfristig begleitet.')+self.benefits([('Kraft erhalten','Krafttraining als Teil deines aktiven Alltags entdecken.'),('Beweglichkeit entwickeln','Bewusste Bewegung und Mobilität in dein Training einbauen.'),('Den Rücken stärken','Dein Trainingsziel mit den Personal Trainern besprechen.'),('Ausdauer aufbauen','Laufband, Ergometer und Crosstrainer in deinem Tempo kennenlernen.'),('Bewusst einsteigen','Fragen stellen und die passende Orientierung für deinen Anfang finden.'),('Menschen ansprechen','Studioleitung, Team und Personal Trainer persönlich kennenlernen.')]))
        body+=self.personal_proof()+self.section('in-deinem-tempo',self.heading('Nicht alles auf einmal.','Ein Anfang,<br>der zu dir passt.')+self.benefits([('Erst kennenlernen','Schau dir das Gym an und bring deine Fragen zum Training mit.'),('Dein Ziel besprechen','Was möchtest du im Alltag leichter machen? Was ist dir wichtig?'),('Deinen Weg finden','Kläre die passende Begleitung und mögliche Termine direkt mit dem Team.')])+f'<div class="actions">{self.b("Unverbindlich Probetraining starten","/probetraining/")}{self.link("Personal Training anfragen","/contact/?thema=Personal%20Training#contact-form")}</div>')+self.family_teaser()+self.final()
        page('/gesund-beweglich/','Gesund & beweglich trainieren | 17/7 Rheinbach','Kraft erhalten, Beweglichkeit entwickeln und bewusst einsteigen. Entdecke persönliches Training für deinen Alltag im Performance Gym Rheinbach.',body,active='/training/')
        body=self.hero('Dein Anfang.<br>Ohne Druck.','Du brauchst keine fertige Trainingsroutine, um bei uns anzufangen. Bring dein Ziel und deine Fragen mit. Den ersten Eindruck bekommst du persönlich.','Neu anfangen',action=('Probetraining starten','/probetraining/'),scroll='So findest du hinein')
        body+=self.section('orientierung',self.heading('Ein Schritt nach dem anderen.','Du musst noch<br>nicht alles wissen.')+self.benefits([('Dein Ziel zählt','Mehr Bewegung, Kraft oder Ausgleich? Starte bei dem, was dir wichtig ist.'),('Fragen sind willkommen','Lerne die Geräte und die Menschen kennen. Sprich uns auf deine Unsicherheiten an.'),('In Ruhe entscheiden','Sieh dir das Gym an und vergleiche danach die Mitgliedschaften. Es gibt auch einen monatlich kündbaren Tarif.')]))+self.personal_proof()+self.c['challenge_promo'](compact=True)+self.section('erster-besuch',self.heading('Dein erster Besuch.','Neugier reicht<br>für den Anfang.')+self.benefits([('Ohne Termin vorbeikommen','Regulär täglich von 06 bis 22 Uhr. An Feiertagen können die Zeiten abweichen.'),('Ausweis und Handtuch einpacken','Melde dich bei deinem ersten Besuch im Studio.'),('Deine Fragen mitbringen','Trainingsziele, Geräte oder Betreuung: Nutze den ersten Besuch zum Kennenlernen.')])+f'<p class="growth-fine">Training ab 14 Jahren. Unter 18 kommst du zum Probetraining bitte mit einem Erziehungsberechtigten.</p>')+self.final()
        page('/neu-anfangen/','Dein Einstieg ins Training | 17/7 Rheinbach','Neu anfangen ohne Druck: Lerne das persönliche Gym in Rheinbach kennen, stelle deine Fragen und entdecke deinen Einstieg ins Training.',body,active='/training/')
        body=self.hero('Dein Ziel.<br>Dein nächstes Level.','Kraft, Ausdauer und Performance. Finde Raum für konzentriertes Training – mit freien Gewichten, Geräten und funktionellen Trainingsflächen.','Fit & stark',self.g[1],('Training entdecken','/training/#kraft'),scroll='Deinem Ziel folgen')
        body+=self.section('deine-richtung',self.heading('Ambitioniert. Auf deine Art.','Was dich<br>weiterbringt.')+self.benefits([('Kraft gezielt trainieren','Zwei Freihantelbereiche und geführte Geräte für unterschiedliche Trainingsweisen.'),('Ausdauer ergänzen','Laufband, Ergometer und Crosstrainer für deine Ausdauereinheiten.'),('Bewegung kombinieren','Nutze die Rigs und freien Flächen für vielseitiges Training.')]))+self.training_section()+self.section('persoenlicher-fokus',self.heading('Ein Blick von außen.','Gemeinsam an<br>deinem Ziel arbeiten.')+f'<p class="growth-lead">Du möchtest dein Training gezielter ausrichten? Lerne Toto, Beatrice und Oliver kennen und besprich Leistungen und Termine direkt mit ihnen.</p><div class="actions">{self.b("Personal Trainer kennenlernen","/unser-team/?filter=personal-trainers#page-content")}</div>')+self.c['challenge_promo'](compact=True)+self.final()
        page('/fit-stark/','Kraft, Ausdauer & Performance | 17/7 Rheinbach','Für ambitioniertes Training in Rheinbach: freie Gewichte, Kraftgeräte, Cardio und Functional Training im persönlichen Warehouse Gym.',body,active='/training/')
        body=self.hero('Mehr als Training.<br>Deine Community.','Gemeinsam anfangen, dranbleiben und Menschen kennenlernen. Entdecke deine WhatsApp-Challenge, persönliche Einladungen und neue Club-Ideen.','Gemeinsam trainieren',action=('Formate entdecken','#clubs'),scroll='Gemeinsam loslegen')
        body+=self.section('clubs',self.heading('Neue Formate. Gemeinsam gedacht.','Finde deine<br>17/7 Community.','Run Club, Cycle Club, Mobility & Stretch und HIIT sind in Planung. Termine, Teilnahme und Konditionen stehen noch nicht fest.')+self.clubs(full=True))+self.c['challenge_promo']()+self.family_teaser()+self.team_section()+self.final()
        page('/community/','Community, Clubs & Challenges | 17/7 Rheinbach','Gemeinsam trainieren bei 17/7: WhatsApp-Challenge, Friends & Family und geplante Run-, Cycle-, Mobility- und HIIT-Formate in Rheinbach.',body,active='/community/')
        body=self.hero('Gemeinsam stärker.<br>Mit deinen Menschen.','Bring deine Mum, deinen Dad oder einen Freund mit zu 17/7. Ein gemeinsamer Anfang beginnt mit einer persönlichen Einladung.','Friends & Family',action=('Einladung erstellen','#einladen'),scroll='So beginnt euer Weg')
        body+=self.section('einladung-erhalten','<div class="invitation-received" id="invitation-received" hidden><p class="eyebrow">Für dich geteilt.</p><h2>Du bist eingeladen.</h2><p id="invitation-greeting"></p><div class="actions">'+self.b('Das Gym kennenlernen','/studio/')+self.link('Gemeinsamen Besuch besprechen','/contact/?thema=Friends%20%26%20Family#contact-form')+'</div><p class="growth-fine">Eine persönliche Einladung zum Kennenlernen. Sie ist kein Gutschein und reserviert keinen kostenlosen Studiozugang.</p></div>','compact')
        body+=self.section('euer-weg',self.heading('Bring your Mum. Dad. Friend.','Einladen.<br>Zusammen anfangen.')+self.benefits([('Persönlich einladen','Erstelle einen eigenen Einladungslink und teile ihn mit einem Menschen, der dir wichtig ist.'),('Gemeinsam kennenlernen','Schaut euch das Gym an. Für ein reguläres Probetraining ist kein Termin nötig.'),('Euren Rhythmus finden','Sprecht über eure Ziele und die Begleitung, die zu eurem gemeinsamen Start passt.'),('Danach entscheiden','Vergleicht die regulären Tarife in Ruhe. Über eine Mitgliedschaft entscheidet jeder selbst.')]))
        body+=self.section('family-challenge',f'<div class="family-planning"><p class="eyebrow">Als nächstes geplant.</p><span class="launch-badge">30-Tage-Family-Challenge · In Planung</span><h2>30 Tage.<br>Ein gemeinsamer Impuls.</h2><p>Die Idee: gemeinsam begleitet trainieren, Kraft, Beweglichkeit und Ausdauer in den Blick nehmen und Fortschritte bewusster wahrnehmen. Start, Betreuung und Konditionen werden noch festgelegt.</p><div class="actions">{self.b("Interesse an der Family-Challenge","/contact/?thema=30-Tage-Family-Challenge#contact-form")}</div></div>','light')
        body+=self.invite_form()+self.final()
        page('/gemeinsam-starten/','Bring Mum, Dad & Friends | 17/7 Rheinbach','Lade deine Mum, deinen Dad oder Freunde mit einem persönlichen Link ein, das Performance Gym Rheinbach kennenzulernen. Gemeinsam stärker starten.',body,active='/community/',mobile=False)
        body=self.hero('Fit im Job.<br>Hier in Rheinbach.','17/7 Firmenfitness für Unternehmen, die Bewegung und persönliche Ansprechpartner in der Nachbarschaft verbinden möchten.','Firmenfitness',self.g[-1],('Firmenfitness anfragen','#firmenanfrage'),scroll='Möglichkeiten entdecken')
        body+=self.section('fuers-team',self.heading('Ein Benefit. Nah am Alltag.','Ein Gym für<br>euer Team.')+self.benefits([('Mitarbeiter-Benefit','Ein persönliches Trainingsangebot in Rheinbach für Beschäftigte gemeinsam besprechen.'),('Firmenkonditionen','Der bestehende Firmen- und Vereinstarif gilt ab fünf Verträgen. Alle Kosten stehen transparent weiter unten.'),('In der Nachbarschaft','Industriestraße 32 a–e. Kostenfreie Parkmöglichkeiten und regulär täglich 06–22 Uhr geöffnet.')]))
        body+=self.section('gemeinsame-aktionen',self.heading('Weitere Möglichkeiten besprechen.','Mehr Bewegung<br>in euer Unternehmen.','Diese Bausteine können Teil eurer Anfrage sein. Umfang und Umsetzung werden individuell geklärt.')+self.benefits([('30-Tage-Challenges','Interesse an einem gemeinsamen Einstieg für eure Mitarbeitenden mitteilen.'),('Gesundheitsaktionen','Ideen für eine Aktion mit dem Team besprechen. Termine und Inhalte werden erst vereinbart.'),('Unternehmenscodes','Einen eigenen Zugangscode für eure Firma anfragen. Es ist noch kein automatisches Code- oder Rabattsystem freigeschaltet.')]))
        plan=next(x for x in self.c['CONTENT']['facts']['membership_plans'] if x['id']=='corporate_club')
        body+=self.section('firmenkonditionen',f'<div class="corporate-terms"><div><p class="eyebrow">Bestehender Firmen- & Vereinstarif</p><h2>Klare Konditionen.<br>Ab fünf Verträgen.</h2><p>12 Monate Laufzeit · monatlich zahlbar</p><p>Zusätzlich einmalig 19,99 € für das E-Band. Keine Aufnahmegebühr. Preise gültig seit 01.02.2026.</p>{self.link("Alle Tarifdetails vergleichen","/preise-aktionen/#corporate_club")}</div><p class="corporate-price">{escape(plan["monthly_eur"].replace(".",","))} €<span>pro Person / Monat</span></p></div>','light')
        body+=self.corporate_form()+self.section('digitaler-einstieg',self.heading('Persönlich abstimmen. Digital vorbereiten.','Euer Weg<br>zur Firmenfitness.')+self.benefits([('Rahmen anfragen','Teamgröße, gewünschte Bausteine und Ansprechpartner mitteilen.'),('Konditionen abstimmen','Die Zuordnung zum Firmentarif wird mit dem Studio geklärt.'),('Anmeldung vorbereiten','Die öffentliche digitale Anmeldung zeigt derzeit reguläre Einzelmitgliedschaften als unverbindliche Demo. Firmenverträge und Codes werden dort noch nicht automatisch verarbeitet.')])+f'<div class="actions">{self.link("Digitale Anmeldung ansehen","/mitglied-werden/#anmeldung")}{self.link("Guido kennenlernen","/staff-member/guido-leffler/")}</div>')
        page('/firmenfitness/','Firmenfitness für Rheinbach | 17/7 Performance Gym','Persönliche Firmenfitness in Rheinbach: Konditionen ab fünf Verträgen, Trainingsangebote fürs Team und individuelle Anfragen für gemeinsame Aktionen.',body,active='/firmenfitness/',mobile=False)
    def invite_form(self):
        return self.section('einladen','''<div class="growth-form-layout"><div><p class="eyebrow">Von dir. Für deine Menschen.</p><h2>Deine Einladung.<br>Ein persönlicher Anfang.</h2><p>Wähle, wen du einladen möchtest. Dein eigener Link führt zu dieser Seite und lässt sich per Messenger, E-Mail oder QR-Code teilen.</p><p class="growth-fine">Kein Benutzerkonto. Keine Kontaktdaten der eingeladenen Person. Die Einladung bucht kein Training.</p></div><div class="growth-form-panel"><form id="invitation-form"><label for="invite-person">Wen möchtest du mitbringen?</label><select id="invite-person" name="person"><option value="mum">Meine Mum</option><option value="dad">Meinen Dad</option><option value="friend">Eine Freundin / einen Freund</option><option value="family">Jemanden aus meiner Familie</option></select><button class="btn dark" type="submit">Meinen Einladungslink erstellen ↗</button></form><div id="invitation-result" hidden><h3>Bereit zum Teilen.</h3><p>Verschicke deine Einladung selbst an die gewünschte Person.</p><label for="invitation-link">Dein Einladungslink</label><input id="invitation-link" type="url" readonly><div class="actions"><button class="btn dark" id="invite-share" type="button" hidden>Einladung teilen ↗</button><button class="btn dark" id="invite-copy" type="button">Link kopieren</button><a class="text-link" id="invite-whatsapp" target="_blank" rel="noopener noreferrer">Mit WhatsApp teilen ↗</a></div><p id="invite-status" class="growth-form-status" role="status"></p><details id="invite-qr-details"><summary>QR-Code zum Weitergeben</summary><div id="invite-qr"></div></details><p class="growth-fine">Wer den Link oder QR-Code erhält, kann die Einladung öffnen. Eine feste Zuordnung zu einem Mitglied, Prämien oder Rabatte sind damit nicht verbunden.</p></div><noscript><p>Teile alternativ diese Seite: /gemeinsam-starten/</p></noscript></div></div>''','growth-form-section')
    def corporate_form(self):
        clubs=''.join(f'<option>{t}</option>' for t in ['Firmenfitness','30-Tage-Challenge','Gesundheitsaktion','Unternehmenscode'])
        return self.section('firmenanfrage','''<div class="growth-form-layout"><div><p class="eyebrow">Euer Team. Eure Möglichkeiten.</p><h2>Lass uns<br>ins Gespräch kommen.</h2><p>Vier kurze Angaben reichen für den ersten Kontakt. Die Website bereitet deine E-Mail vor; du sendest sie anschließend selbst in deinem E-Mail-Programm.</p><p class="growth-fine">Keine automatische Buchung. Keine Anmeldung zu einem Verteiler.</p><a class="text-link" href="tel:+4922269111999">Lieber anrufen: 02226 91 11 999 ↗</a></div><form id="corporate-form" class="growth-form-panel"><div class="field"><label for="company">Unternehmen *</label><input id="company" name="company" autocomplete="organization" required maxlength="120"></div><div class="growth-form-two"><div class="field"><label for="company-size">Interessierte Mitarbeitende *</label><select id="company-size" name="size" required><option value="">Bitte wählen</option><option>Unter 5</option><option>5–10</option><option>11–25</option><option>26–50</option><option>Mehr als 50</option></select></div><div class="field"><label for="company-interest">Euer Schwerpunkt *</label><select id="company-interest" name="interest" required>'''+clubs+'''</select></div></div><div class="field"><label for="company-email">Geschäftliche E-Mail *</label><input id="company-email" name="email" type="email" autocomplete="email" required maxlength="150"></div><div class="field"><label for="company-message">Was möchtest du uns noch mitgeben? (optional)</label><textarea id="company-message" name="message" rows="3" maxlength="1500"></textarea></div><button class="btn dark" type="submit">Firmenanfrage vorbereiten ↗</button><p class="growth-fine">* Pflichtfelder. Die Angaben bleiben bis zum Öffnen des E-Mail-Programms in diesem Browser. <a href="/datenschutzerklaerung/#einladungen-firmenanfragen">Datenschutzhinweise</a></p><section id="corporate-prepared" class="growth-prepared" hidden aria-labelledby="corporate-ready"><h3 id="corporate-ready" tabindex="-1">Deine Anfrage ist vorbereitet.</h3><p>Noch nicht versendet. Öffne die E-Mail und sende sie dort selbst ab.</p><pre id="corporate-preview"></pre><div class="actions"><a id="corporate-open" class="btn dark" href="mailto:info@performance-gym.de">E-Mail-Programm öffnen ↗</a><button id="corporate-copy" type="button" class="text-link">Text kopieren</button></div><p id="corporate-status" role="status" class="growth-form-status"></p></section><noscript><p>Schreibe direkt an <a href="mailto:info@performance-gym.de">info@performance-gym.de</a> oder rufe uns an.</p></noscript></form></div>''','growth-form-section')

GROWTH_PRIVACY='''<h2 id="einladungen-firmenanfragen">Persönliche Einladungen und Firmenanfragen</h2><p>Eine persönliche Einladung erstellt im Browser einen zufälligen Link mit dem gewählten Einladungstyp. Es werden keine Kontaktdaten der eingeladenen Person abgefragt. Der Link enthält keine Zuordnung zu einem Mitgliedskonto und wird nicht für Prämien oder Rabatte ausgewertet. Wer den Link erhält, kann die Einladung öffnen. Beim Aufruf können die URL-Bestandteile wie andere Seitenaufrufe in technischen Serverprotokollen erscheinen. Die Website führt keine Einladungsstatistik.</p><p>Du entscheidest selbst, ob du den Link kopierst oder über eine andere Anwendung teilst. Beim Öffnen der WhatsApp-Teilen-Funktion wird der Einladungstext an WhatsApp übergeben; du wählst dort den Empfänger und sendest die Nachricht selbst. Der QR-Code wird lokal berechnet.</p><p>Das Firmenfitness-Formular erstellt eine E-Mail ausschließlich in deinem Browser. Angaben zu Unternehmen, Teamgröße, Schwerpunkt und E-Mail-Adresse werden nicht als Formular an einen Website-Server gesendet. Erst beim Öffnen deines E-Mail-Programms werden sie an dieses übergeben; die Nachricht sendest du anschließend selbst.</p>'''
